# Ansible playbook to install Neovim config dependencies.
# Run automatically by the Neovim configuration if ansible-playbook is found.
# Currently only works for Fedora.
- name: Install all Neovim config dependencies
  hosts: localhost
  tasks:
    - name: Install clipboard handlers
      become: yes
      ansible.builtin.dnf:
        name:
          - xclip
          - wl-clipboard

    - name: Install ripgrep and fd (for 'grepprg' and Telescope)
      become: yes
      ansible.builtin.dnf:
        name:
          - ripgrep
          - fd-find

    - name: Install libsqlite (for Telescope smart history)
      become: yes
      ansible.builtin.dnf:
        name: sqlite-devel
