-- Configure plugins and features that depend on plugins
require('config.colorscheme')
require('config.presence')
require('config.godot')
require('config.undotree')
require('config.nvim_tree')
require('config.colorizer')
require('config.vcoolor')
require('config.fugitive_gv')
require('config.startify')
require('config.barbar')
require('config.gitgutter')
require('config.tree-sitter')
require('config.telescope-nvim')
