require('config.utility.colorizer')
require('config.utility.tree-sitter')
require('config.utility.rooter')
require('config.utility.markdown-preview')
require('config.utility.nvim-toggleterm')
require('config.utility.kommentary')
