require('config.utility.tree-sitter')
require('config.utility.nvim-compe')
require('config.utility.rooter')
require('config.utility.markdown-preview')
require('config.utility.kommentary')
require('config.utility.whichkey')
